on:
  push:
    branches:
      - main
      - backport-fix-to-1.0.1

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:          
          release-type: helm
          package-name: hello-world
          versioning-strategy: always-bump-patch
